site_name: GeminiTeacher
repo_url: https://github.com/supersheepbear/GeminiTeacher
site_url: https://supersheepbear.github.io/GeminiTeacher
site_description: An educational content generation toolkit powered by Google's Gemini LLM. Transform raw text into structured, well-organized educational courses with minimal effort.
site_author: Sheepbear
edit_uri: edit/main/docs/
repo_name: supersheepbear/GeminiTeacher
copyright: Maintained by <a href="https://supersheepbear.com">supersheepbear</a>.

nav:
  - Home: index.md
  - Usage Guide: usage.md
  - Modules:
    - Overview: modules.md
    - Core Modules: modules.md#core-modules
    - Command-line App: modules.md#command-line-application-geminiteacherapp
    - Data Models: modules.md#data-models
  - Parallel Processing: parallel.md
  - CLI Application: app.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/geminiteacher"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/supersheepbear/GeminiTeacher
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/geminiteacher

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
