site_name: CascadeLLM
repo_url: https://github.com/supersheepbear/CascadeLLM
site_url: https://supersheepbear.github.io/CascadeLLM
site_description: cascade LLM prompts by request LLM itself to create prompts and then send the generated prompts back for further LLM answers
site_author: Sheepbear
edit_uri: edit/main/docs/
repo_name: supersheepbear/CascadeLLM
copyright: Maintained by <a href="https://supersheepbear.com">supersheepbear</a>.

nav:
  - Home: index.md
  - Modules: modules.md
  - Course Generator: coursemaker.md
  - Parallel Processing: parallel.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/cascadellm"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/supersheepbear/CascadeLLM
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/CascadeLLM

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
