# Gemini API Configuration
api:
  google_api_key: "your_gemini_api_key_here"  # Replace with your actual API key

# Model Settings
model:
  name: "gemini-1.5-pro"  # Model name
  temperature: 0.2        # Controls randomness (0.0 to 1.0)

# Course Generation Settings
course:
  output_dir: "output"    # Directory to save generated courses 